name = "zenn-trend-history"
compatibility_date = "2023-12-01"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "zenn-trend-history"
database_id = "7728c557-2945-41b2-92f4-b5ea14f46139"
preview_database_id = "DB"

# Cron Triggers - once a day
[triggers]
crons = ["0 0 * * *"]